export const libros = {
  "Génesis": "libros/genesis.js",
  "Éxodo": "libros/exodo.js",
  "Levítico": "libros/levitico.js",
  "Números": "libros/numeros.js",
  "Deuteronomio": "libros/deuteronomio.js",
  "Josué": "libros/josue.js",
  "Jueces": "libros/jueces.js",
  "Ruth": "libros/ruth.js",
  "1 Samuel": "libros/1_samuel.js",
  "2 Samuel": "libros/2_samuel.js",
  "1 Reyes": "libros/1_reyes.js",
  "2 Reyes": "libros/2_reyes.js",
  "1 Crónicas": "libros/1_cronicas.js",
  "2 Crónicas": "libros/2_cronicas.js",
  "Esdras": "libros/esdras.js",
  "Nehemías": "libros/nehemias.js",
  "Ester": "libros/ester.js",
  "Job": "libros/job.js",
  "Salmos": "libros/salmos.js",
  "Proverbios": "libros/proverbios.js",
  "Eclesiastés": "libros/eclesiastes.js",
  "Cantares": "libros/cantares.js",
  "Isaias": "libros/isaias.js",
  "Jeremías": "libros/jeremias.js",
  "Lamentaciones": "libros/lamentaciones.js",
  "Ezequiel": "libros/ezequiel.js",
  "Daniel": "libros/daniel.js",
  "Oseas": "libros/oseas.js",
  "Joel": "libros/joel.js",
  "Amós": "libros/amos.js",
  "Abdías": "libros/abdias.js",
  "Jonás": "libros/jonas.js",
  "Miqueas": "libros/miqueas.js",
  "Nahúm": "libros/nahum.js",
  "Habacuc": "libros/habacuc.js",
  "Sofonías": "libros/sofonias.js",
  "Zacarías": "libros/zacarias.js",
  "Malaquías": "libros/malaquias.js",
  // Nuevo Testamento
  "S.Mateo": "libros/mateo.js",
  "S.Marcos": "libros/marcos.js",
  "S.Lucas": "libros/lucas.js",
  "Hechos": "libros/hechos.js",
  "Romanos": "libros/romanos.js",
  "1 Corintios": "libros/1_corintios.js",
  "2 Corintios": "libros/2_corintios.js",
  "Gálatas": "libros/galatas.js",
  "Efesios": "libros/efesios.js",
  "Filipenses": "libros/filipenses.js",
  "Colosenses": "libros/colosenses.js",
  "1 Tesalonicenses": "libros/1_tesalonicenses.js",
  "2 Tesalonicenses": "libros/2_tesalonicenses.js",
  "1 Timoteo": "libros/1_timoteo.js",
  "2 Timoteo": "libros/2_timoteo.js",
  "Tito": "libros/tito.js",
  "Filemón": "libros/filemon.js",
  "Hebreos": "libros/hebreos.js",
  "Santiago": "libros/Santiago.js",
  "1 Pedro": "libros/1_pedro.js",
  "2 Pedro": "libros/2_pedro.js",
  "1 Juan": "libros/1_juan.js",
  "2 Juan": "libros/2_juan.js",
  "3 Juan": "libros/3_juan.js",
  "Judas": "libros/judas.js",
  "Apocalipsis": "libros/apocalipsis.js",
};
