export default [

  // Isaías 1
  [
    'Visión que recibió Isaías hijo de Amoz acerca de Judá y Jerusalén, durante los reinados de Uzías, Jotán, Acaz y Ezequías, reyes de Judá.',
    '¡Oigan, cielos! ¡Escucha, tierra! Así dice el Señor: «Yo crié hijos hasta hacerlos hombres, pero ellos se rebelaron contra mí.»',
    'El buey conoce a su dueño y el asno el pesebre de su amo; ¡pero Israel no conoce, mi pueblo no entiende!»',
    '¡Ay, nación pecadora, pueblo cargado de culpa, generación de malhechores, hijos corruptos! ¡Han abandonado al Señor! ¡Han despreciado al Santo de Israel! ¡Se han vuelto atrás!',
    '¿Para qué recibir más golpes? ¿Para qué insistir en la rebelión? Toda su cabeza está herida, todo su corazón está enfermo.',
    'Desde la planta del pie hasta la coronilla no les queda nada sano: todo en ellos son heridas, moretones y llagas abiertas, que no les han sido curadas ni vendadas, ni aliviadas con aceite.',
    'Su país está desolado, sus ciudades son presa del fuego; ante sus propios ojos los extraños devoran sus campos; su país está desolado, como si hubiera sido destruido por extranjeros.',
    'La bella Sión ha quedado como cobertizo en un viñedo, como choza en un melonar, como ciudad sitiada.',
    'Si el Señor Todopoderoso no nos hubiera dejado algunos sobrevivientes, seríamos ya como Sodoma, nos pareceríamos a Gomorra.',
    '¡Oigan la palabra del Señor, gobernantes de Sodoma! ¡Escuchen la enseñanza de nuestro Dios, pueblo de Gomorra!',
    '«¿De qué me sirven sus muchos sacrificios? —dice el Señor—. Harto estoy de holocaustos de carneros y de la grasa de animales engordados; la sangre de toros, corderos y cabras no me complace.»',
    '¿Por qué vienen a presentarse ante mí? ¿Quién les mandó traer animales para que pisotearan mis atrios?',
    'No me sigan trayendo vanas ofrendas; el incienso es para mí una abominación. Luna nueva, día de reposo, asambleas convocadas; ¡no soporto que con su adoración me ofendan!',
    'Yo aborrezco sus lunas nuevas y festividades; se me han vuelto una carga que estoy cansado de soportar.',
    'Cuando levantan sus manos, yo aparto de ustedes mis ojos; aunque multipliquen sus oraciones, no las escucharé, pues tienen las manos llenas de sangre.',
    '¡Lávense, límpiense! ¡Aparten de mi vista sus obras malvadas! ¡Dejen de hacer el mal!',
    '¡Aprendan a hacer el bien! ¡Busquen la justicia y reprendan al opresor! ¡Aboguen por el huérfano y defiendan a la viuda!',
    '»Vengan, pongamos las cosas en claro —dice el Señor—. ¿Son sus pecados como escarlata? ¡Quedarán blancos como la nieve! ¿Son rojos como la púrpura? ¡Quedarán como la lana!',
    '¿Están ustedes dispuestos a obedecer? ¡Comerán lo mejor de la tierra!',
    '¿Se niegan y se rebelan? ¡Serán devorados por la espada!» El Señor mismo lo ha dicho.',
    '¡Cómo se ha prostituido la ciudad fiel! Antes estaba llena de justicia. La rectitud moraba en ella, pero ahora sólo quedan asesinos.',
    'Tu plata se ha convertido en escoria; tu buen vino, en agua.',
    'Tus gobernantes son rebeldes, cómplices de ladrones; todos aman el soborno y van detrás de las prebendas. No abogan por el huérfano, ni se ocupan de la causa de la viuda.',
    'Por eso afirma el Señor, el Señor Todopoderoso, el Fuerte de Israel: «Me desquitaré de mis adversarios, me vengaré de mis enemigos.»',
    'Volveré mi mano contra ti, limpiaré tus escorias con lejía y quitaré todas tus impurezas.',
    'Restauraré a tus jueces como al principio, y a tus consejeros como al comienzo. Entonces serás llamada Ciudad de justicia, Ciudad fiel.',
    'Sión será redimida con justicia, y con rectitud, los que se arrepientan.',
    'Pero los rebeldes y pecadores a una serán quebrantados, y perecerán los que abandonan al Señor.',
    'Se avergonzarán de las encinas que ustedes tanto aman; los jardines que eligieron serán para ellos una afrenta.',
    'Serán como una encina con hojas marchitas, como un jardín sin agua.',
    'El hombre fuerte se convertirá en estopa, y su trabajo en chispa; arderán los dos juntos, y no habrá quien los apague.'
  ],

  // Isaías 2
  [
    'Palabra que Isaías hijo de Amoz recibió en visión acerca de Judá y Jerusalén:',
    'En los últimos días, el monte de la casa del Señor será establecido como el más alto de los montes; se alzará por encima de las colinas, y hacia él confluirán todas las naciones.',
    'Muchos pueblos vendrán y dirán: «¡Vengan, subamos al monte del Señor, a la casa del Dios de Jacob!, para que nos enseñe sus caminos y andemos por sus sendas.» Porque de Sión saldrá la enseñanza, de Jerusalén la palabra del Señor.',
    'Él juzgará entre las naciones y será árbitro de muchos pueblos. Convertirán sus espadas en arados y sus lanzas en hoces. No levantará espada nación contra nación, y nunca más se adiestrarán para la guerra.',
    '¡Ven, pueblo de Jacob, y caminemos a la luz del Señor!',
    'Has abandonado a tu pueblo, a los descendientes de Jacob, porque están llenos de astrólogos de Oriente, de adivinos como entre los filisteos, y hacen tratos con extranjeros.',
    'Su tierra está llena de oro y plata, y sus tesoros son incalculables. En su tierra abundan los caballos, y sus carros de guerra son incontables.',
    'Su país está lleno de ídolos; el pueblo adora la obra de sus manos, lo que han hecho con sus propios dedos.',
    'Al hombre se le humilla, a la humanidad se le degrada. ¡Imposible que los perdones!',
    '¡Métete en la roca, y escóndete en el polvo ante el terror del Señor y el esplendor de su majestad!',
    'Los ojos del altivo serán humillados y la arrogancia humana será doblegada. ¡En aquel día sólo el Señor será exaltado!',
    'Un día vendrá el Señor Todopoderoso contra todos los orgullosos y arrogantes, contra todos los altaneros, para humillarlos;',
    'contra todos los cedros del Líbano, arrogantes y erguidos, contra todas las encinas de Basán,',
    'contra todas las montañas altivas, contra todas las colinas erguidas,',
    'contra todas las torres altas, contra todo muro fortificado,',
    'contra todas las naves de Tarsis, contra todos los barcos lujosos.',
    'La altivez del hombre será abatida, y la arrogancia humana será humillada. En aquel día sólo el Señor será exaltado,',
    'y los ídolos desaparecerán por completo.',
    'Los hombres se meterán en las cuevas de las rocas, y en las grietas del suelo, ante el terror del Señor y el esplendor de su majestad, cuando él se levante para hacer temblar la tierra.',
    'En aquel día arrojará el hombre a los topos y murciélagos, a sus ídolos de oro y plata que él fabricó para adorarlos.',
    'Se meterá en las grutas de las rocas y en las hendiduras de los peñascos, ante el terror del Señor y el esplendor de su majestad, cuando él se levante para hacer temblar la tierra.',
    '¡Dejen de confiar en el hombre, que es muy poco lo que vale! ¡Su vida es un soplo nada más!'
  ],

  // Isaías 3
  [
    '¡Presten atención! El Señor, el Señor Todopoderoso, retira de Jerusalén y de Judá todo apoyo y sustento: toda provisión de pan, toda provisión de agua.',
    'Él retira al valiente y al guerrero, al juez y al profeta, al adivino y al anciano,',
    'al capitán y al dignatario, al consejero, al artesano experto y al hábil encantador.',
    'Les pondré como jefes a muchachos, y los gobernarán niños caprichosos.',
    'Unos a otros se maltratarán: hombre contra hombre, vecino contra vecino, joven contra anciano, plebeyo contra noble.',
    'Entonces un hombre agarrará a su hermano en la casa de su padre, y le dirá: «Sé nuestro líder, pues tienes un manto; ¡hazte cargo de este montón de ruinas!»',
    'Pero entonces el otro protestará: «Yo no soy médico, y en mi casa no hay pan ni manto; ¡no me hagas líder del pueblo!»',
    'Jerusalén se tambalea, Judá se derrumba, porque su hablar y su actuar son contrarios al Señor: ¡desafían su gloriosa presencia!',
    'Su propio descaro los acusa y, como Sodoma, se jactan de su pecado; ¡ni siquiera lo disimulan! ¡Ay de ellos, porque causan su propia desgracia!',
    'Díganle al justo que le irá bien, pues gozará del fruto de sus acciones.',
    '¡Ay del malvado, pues le irá mal! ¡Según la obra de sus manos se le pagará!',
    '¡Pobre pueblo mío, oprimido por niños y gobernado por mujeres! ¡Pobre pueblo mío, extraviado por tus guías, que tuercen el curso de tu senda!',
    'El Señor se dispone a denunciar; se levanta para enjuiciar al pueblo.',
    'El Señor entra en juicio contra los ancianos y jefes de su pueblo: «¡Ustedes han devorado la viña, y el despojo del pobre está en sus casas!',
    '¿Con qué derecho aplastan a mi pueblo y pasan por encima de los pobres?» afirma el Señor, el Señor Todopoderoso.',
    'El Señor dice: «Las hijas de Sión son tan orgullosas que caminan con el cuello estirado, con ojos seductores y pasitos cortos, haciendo sonar los adornos de sus pies.',
    'Por eso el Señor cubrirá de sarna la cabeza de las hijas de Sión; el Señor las dejará completamente calvas.»',
    'En aquel día, el Señor arrancará todo adorno: hebillas, diademas, broches,',
    'pendientes, pulseras, velos,',
    'pañuelos, cadenillas de los pies, cinturones, frasquitos de perfume, amuletos,',
    'anillos, argollas para la nariz,',
    'ropas de gala, mantos, chales, bolsos,',
    'espejos, telas finas, turbantes y mantillas.',
    'Habrá pestilencia en vez de perfume, soga en vez de cinturón, calvicie en vez de peinado elegante, ropa de luto en vez de trajes lujosos, vergüenza en vez de belleza.',
    'Tus hombres caerán a filo de espada, y tus valientes, en el campo de batalla.',
    'Las puertas de la ciudad gemirán y se vestirán de luto; desolada, la ciudad se sentará en el suelo.'
  ],

  // Isaías 4
  [
    'En aquel día, siete mujeres agarrarán a un solo hombre y le dirán: «De alimentarnos y de vestirnos nosotras nos ocuparemos; tan sólo déjanos llevar tu nombre: ¡Líbranos de nuestra afrenta!»',
    'En aquel día, el retoño del Señor será bello y glorioso, y el fruto de la tierra será el orgullo y el honor de los sobrevivientes de Israel.',
    'Entonces tanto el que quede en Sión como el que sobreviva en Jerusalén serán llamados santos, e inscritos para vida en Jerusalén.',
    'Con espíritu de juicio y espíritu abrasador, el Señor lavará la inmundicia de las hijas de Sión y limpiará la sangre que haya en Jerusalén.',
    'Entonces el Señor creará una nube de humo durante el día y un resplandor de fuego llameante durante la noche, sobre el monte Sión y sobre los que allí se reúnan. Por sobre toda la gloria habrá un toldo',
    'que servirá de cobertizo, para dar sombra contra el calor del día, y de refugio y protección contra la lluvia y la tormenta.'
  ],

  // Isaías 5
  [
    'Cantaré en nombre de mi amigo querido una canción dedicada a su viña. Mi amigo querido tenía una viña en una ladera fértil.',
    'La cavó, la limpió de piedras y la plantó con las mejores cepas. Edificó una torre en medio de ella y además preparó un lagar. Él esperaba que diera buenas uvas, pero acabó dando uvas agrias.',
    'Y ahora, hombres de Judá, habitantes de Jerusalén, juzguen entre mi viña y yo.',
    '¿Qué más se podría hacer por mi viña que yo no lo haya hecho? Yo esperaba que diera buenas uvas; ¿por qué dio uvas agrias?',
    'Voy a decirles lo que haré con mi viña: Le quitaré su cerco, y será destruida; derribaré su muro, y será pisoteada.',
    'La dejaré desolada, y no será podada ni cultivada; le crecerán espinos y cardos. Mandaré que las nubes no lluevan sobre ella.',
    'La viña del Señor Todopoderoso es el pueblo de Israel; los hombres de Judá son su huerto preferido. Él esperaba justicia, pero encontró ríos de sangre; esperaba rectitud, pero encontró gritos de angustia.',
    '¡Ay de aquellos que acaparan casa tras casa y se apropian de campo tras campo hasta que no dejan lugar para nadie más, y terminan viviendo solos en el país!',
    'El Señor Todopoderoso me ha dicho al oído: «Muchas casas quedarán desoladas, y no habrá quien habite las grandes mansiones.»',
    'Tres hectáreas de viña sólo producirán un tonel, y diez medidas de semilla darán tan sólo una.',
    '¡Ay de los que madrugan para ir tras bebidas embriagantes, que quedan hasta muy tarde embriagándose con vino!',
    'En sus banquetes hay vino y arpas, liras, tambores y flautas; pero no se fijan en los hechos del Señor ni tienen en cuenta las obras de sus manos.',
    'Por eso mi pueblo será exiliado porque no me conoce; sus nobles perecerán de hambre y la multitud se morirá de sed.',
    'Por eso el sepulcro ensancha su garganta, y desmesuradamente abre sus fauces. Allí bajan nobles y plebeyos, con sus juergas y diversiones.',
    'El hombre será humillado, la humanidad, doblegada, y abatidos los ojos altivos.',
    'Pero el Señor Todopoderoso será exaltado en justicia, el Dios santo se mostrará santo en rectitud.',
    'Los corderos pastarán como en praderas propias, y las cabras comerán entre las ruinas de los ricos.',
    '¡Ay de los que arrastran iniquidad con cuerdas de mentira, y el pecado con sogas de carreta!',
    'Dicen: «¡Que Dios se apure, que apresure su obra para que la veamos; que se acerque y se cumpla el plan del Santo de Israel, para que lo conozcamos!»',
    '¡Ay de los que llaman a lo malo bueno y a lo bueno malo, que tienen las tinieblas por luz y la luz por tinieblas, que tienen lo amargo por dulce y lo dulce por amargo!',
    '¡Ay de los que se consideran sabios, de los que se creen inteligentes!',
    '¡Ay de los valientes para beber vino, de los valentones que mezclan bebidas embriagantes,',
    'de los que por soborno absuelven al culpable, y le niegan sus derechos al indefenso!',
    'Por eso, así como las lenguas de fuego devoran la paja y el pasto seco se consume en las llamas, su raíz se pudrirá y, como el polvo, se disipará su flor. Porque han rechazado la ley del Señor Todopoderoso y han desdeñado la palabra del Santo de Israel.',
    'Por eso se enciende la ira del Señor contra su pueblo, levanta la mano contra él y lo golpea; las montañas se estremecen, los cadáveres quedan como basura en medio de las calles. Con todo, no se aplacó su ira, y su brazo aún sigue extendido.',
    'Con una bandera le hará señas a una nación lejana, con un silbido la llamará desde el extremo de la tierra, y esta nación llegará presta y veloz.',
    'Ninguno de ellos se cansa ni tropieza, ni dormita ni se duerme; a ninguno se le afloja el cinturón ni se le rompe la correa de las sandalias.',
    'Sus flechas son puntiagudas, tensos todos sus arcos; parecen pedernal los cascos de sus caballos, y torbellino las ruedas de sus carros.',
    'Su rugido es el de una leona, como el de los leoncillos: gruñe y atrapa la presa, y se la lleva sin que nadie se la arrebate.',
    'En aquel día bramará contra ella como brama el mar. Si alguien contempla la tierra, la verá sombría y angustiada, y la luz se ocultará tras negros nubarrones.'
  ],

  // Isaías 6
  [
    'El año de la muerte del rey Uzías, vi al Señor excelso y sublime, sentado en un trono; las orlas de su manto llenaban el templo.',
    'Por encima de él había serafines, cada uno de los cuales tenía seis alas: con dos de ellas se cubrían el rostro, con dos se cubrían los pies, y con dos volaban.',
    'Y se decían el uno al otro: «Santo, santo, santo es el Señor Todopoderoso; toda la tierra está llena de su gloria.»',
    'Al sonido de sus voces, se estremecieron los umbrales de las puertas y el templo se llenó de humo.',
    'Entonces grité: «¡Ay de mí, que estoy perdido! Soy un hombre de labios impuros y vivo en medio de un pueblo de labios blasfemos, ¡y no obstante mis ojos han visto al Rey, al Señor Todopoderoso!»',
    'En ese momento voló hacia mí uno de los serafines. Traía en la mano una brasa que, con unas tenazas, había tomado del altar.',
    'Con ella me tocó los labios y me dijo: «Mira, esto ha tocado tus labios; tu maldad ha sido borrada, y tu pecado, perdonado.»',
    'Entonces oí la voz del Señor que decía: ¿A quién enviaré? ¿Quién irá por nosotros? Y respondí: Aquí estoy. ¡Envíame a mí!',
    'Él dijo: Ve y dile a este pueblo: »Oigan bien, pero no entiendan; miren bien, pero no perciban.',
    'Haz insensible el corazón de este pueblo; embota sus oídos y cierra sus ojos, no sea que vea con sus ojos, oiga con sus oídos, y entienda con su corazón, y se convierta y sea sanado.',
    'Entonces exclamé: ¿Hasta cuándo, Señor? Y él respondió: «Hasta que las ciudades queden destruidas y sin habitante alguno; hasta que las casas queden deshabitadas, y los campos, asolados y en ruinas;',
    'hasta que el Señor haya enviado lejos a todo el pueblo, y el país quede en total abandono. Y si aún queda en la tierra una décima parte, ésta volverá a ser devastada.»'
  ],

  // Isaías 7
  [
    'Acaz, hijo de Jotán y nieto de Uzías, reinaba en Judá. En ese tiempo Rezín, rey de Aram, y Pecaj hijo de Remalías, rey de Israel, subieron contra Jerusalén para atacarla, pero no pudieron conquistarla.',
    'En el palacio de David se recibió la noticia de que Aram se había aliado con Efraín, y se estremeció el corazón de Acaz y el de su pueblo, como se estremecen por el viento los árboles del bosque.',
    'El Señor le dijo a Isaías: «Ve con tu hijo Sear Yasub a encontrarte con Acaz donde termina el canal del estanque superior, en el camino que conduce al Campo del Lavandero.»',
    'Dile que tenga cuidado y no pierda la calma; que no tema ante el enojo ardiente de Rezín el sirio, ni ante el hijo de Remalías; que no se descorazone a causa de esos dos tizones humeantes.',
    'Dile también que Efraín, junto con el hijo de Remalías y el sirio, han tramado hacerle mal, pues piensan',
    'subir contra Judá, provocar el pánico, conquistarla y poner allí como rey al hijo de Tabel.',
    'Pero dile además que yo, el Señor omnipotente, digo: »Eso no se cumplirá ni sucederá.',
    'La cabeza de Aram es Damasco, y la cabeza de Damasco es Rezín; pero dentro de sesenta y cinco años Efraín será destrozado hasta dejar de ser pueblo.',
    'La cabeza de Efraín es Samaria, y la cabeza de Samaria es el hijo de Remalías; si ustedes no creen en mí, no permanecerán firmes.»',
    'El Señor se dirigió a Acaz de nuevo:',
    '«Pide que el Señor tu Dios te dé una señal, ya sea en lo más profundo de la tierra o en lo más alto del cielo.»',
    'Pero Acaz respondió: «No pondré a prueba al Señor, ni le pediré nada.»',
    'Entonces Isaías dijo: «¡Escuchen ahora ustedes, los de la dinastía de David! ¿No les basta con agotar la paciencia de los hombres, que hacen lo mismo con mi Dios?»',
    '«Por eso, el Señor mismo les dará una señal: La joven concebirá y dará a luz un hijo, y lo llamará Emanuel.»',
    '«Cuando sepa elegir lo bueno y rechazar lo malo, comerá cuajada con miel.»',
    '«Porque antes de que el niño sepa elegir lo bueno y rechazar lo malo, la tierra de los dos reyes que tú temes quedará abandonada.»',
    '»El Señor hará venir sobre ti, sobre tu pueblo y sobre la dinastía de tu padre, días como no se conocieron desde que Efraín se separó de Judá, pues hará venir al rey de Asiria.»',
    'En aquel día el Señor llamará con un silbido a la mosca que está en los lejanos ríos de Egipto, y a la abeja que está en la tierra de Asiria.',
    'Todas ellas vendrán y anidarán en las quebradas profundas, en las hendiduras de las rocas, en todos los matorrales espinosos y sobre todos los abrevaderos.',
    'En aquel día, con el rey de Asiria como navaja prestada del otro lado del río Éufrates, el Señor le afeitará a Israel la cabeza y el vello púbico, y también la barba.',
    'En aquel día, un hombre criará un ternero y dos cabras;',
    'y le darán tanta leche que tendrá leche cuajada para comer. Además, todos los que permanezcan en la tierra comerán cuajada con miel.',
    'En aquel día, allí donde hubo mil viñedos que costaban mil monedas de plata cada uno, no quedarán más que zarzas y espinos,',
    'los cuales cubrirán toda la tierra. Sólo se podrá entrar allí con arco y flecha.',
    'Y por temor a estos espinos y a estas zarzas, ya no irás a los cerros que antes se cultivaban con el azadón, pues se convertirán en lugares donde se suelta el ganado y corretean las ovejas.'
  ],

  // Isaías 8
  [
    'El Señor me dijo: «Toma una tablilla grande y, con un estilete común, escribe sobre ella: Tocante a Maher Salal Jasbaz.»',
    '«Yo convocaré como testigos confiables al sacerdote Urías y a Zacarías hijo de Jeberequías.»',
    'Luego tuve relaciones con la profetisa, y ella concibió y dio a luz un hijo. Entonces el Señor me dijo: «Ponle por nombre Maher Salal Jasbaz.»',
    '«Antes de que el niño aprenda a decir papá y mamá, la riqueza de Damasco y el botín de Samaria serán llevados ante el rey de Asiria.»',
    'El Señor volvió a decirme:',
    '«Por cuanto este pueblo ha rechazado las mansas corrientes de Siloé y se regocija con Rezín y con el hijo de Remalías,',
    'el Señor está a punto de traer contra ellos las impetuosas crecientes del río Éufrates: al rey de Asiria con toda su gloria. Rebasará todos sus canales, desbordará todas sus orillas;',
    'pasará hasta Judá, la inundará, y crecerá hasta llegarle al cuello. Sus alas extendidas, ¡oh Emanuel!, cubrirán la anchura de tu tierra.»',
    'Escuchen esto, naciones, todas las naciones lejanas: ¡Alcen el grito de guerra, y serán destrozadas! ¡Prepárense para la batalla, y serán despedazadas! ¡Prepárense para la batalla, y serán desmenuzadas!',
    'Tracen su estrategia, pero será desbaratada; propongan su plan, pero no se realizará, porque Dios está con nosotros.',
    'El Señor me habló fuertemente y me advirtió que no siguiera el camino de este pueblo. Me dijo:',
    '«No digan ustedes que es conspiración todo lo que llama conspiración esta gente; no teman lo que ellos temen, ni se dejen asustar.',
    'Sólo al Señor Todopoderoso tendrán ustedes por santo, sólo a él deben honrarlo, sólo a él han de temerlo.',
    'El Señor será un santuario. Pero será una piedra de tropiezo para las dos casas de Israel; ¡una roca que los hará caer! ¡Será para los habitantes de Jerusalén un lazo y una trampa!',
    'Muchos de ellos tropezarán; caerán y serán quebrantados. Se les tenderán trampas, y en ellas quedarán atrapados.»',
    'Guarda bien el testimonio; sella la ley entre mis discípulos.',
    'El Señor ha escondido su rostro del pueblo de Jacob, pero yo esperaré en él, pues en él tengo puesta mi esperanza.',
    'Aquí me tienen, con los hijos que el Señor me ha dado. Somos en Israel señales y presagios del Señor Todopoderoso, que habita en el monte Sión.',
    'Si alguien les dice: «Consulten a las pitonisas y a los agoreros que susurran y musitan; ¿acaso no es deber de un pueblo consultar a sus dioses y a los muertos, en favor de los vivos?»',
    'yo les digo: «¡Aténganse a la ley y al testimonio!» Para quienes no se atengan a esto, no habrá un amanecer.',
    'Ustedes habrán de enfurecerse cuando, angustiados y hambrientos, vaguen por la tierra. Levantando los ojos al cielo, maldecirán a su rey y a su Dios,',
    'y clavando la mirada en la tierra, sólo verán aflicción, tinieblas y espantosa penumbra; ¡serán arrojados a una oscuridad total!'
  ],

  // Isaías 9
  [
    'A pesar de todo, no habrá más penumbra para la que estuvo angustiada. En el pasado Dios humilló a la tierra de Zabulón y a la tierra de Neftalí; pero en el futuro honrará a Galilea, tierra de paganos, en el camino del mar, al otro lado del Jordán.',
    'El pueblo que andaba en la oscuridad ha visto una gran luz; sobre los que vivían en densas tinieblas la luz ha resplandecido.',
    'Tú has hecho que la nación crezca; has aumentado su alegría. Y se alegran ellos en tu presencia como cuando recogen la cosecha, como cuando reparten el botín.',
    'Ciertamente tú has quebrado, como en la derrota de Madián, el yugo que los oprimía, la barra que pesaba sobre sus hombros, el bastón de mando que los subyugaba.',
    'Todas las botas guerreras que resonaron en la batalla, y toda la ropa teñida en sangre serán arrojadas al fuego, serán consumidas por las llamas.',
    'Porque nos ha nacido un niño, se nos ha concedido un hijo; la soberanía reposará sobre sus hombros, y se le darán estos nombres: Consejero admirable, Dios fuerte, Padre eterno, Príncipe de paz.',
    'Se extenderán su soberanía y su paz, y no tendrán fin. Gobernará sobre el trono de David y sobre su reino, para establecerlo y sostenerlo con justicia y rectitud desde ahora y para siempre. Esto lo llevará a cabo el celo del Señor Todopoderoso.',
    'El Señor ha enviado su palabra; la ha enviado contra Jacob, ¡ya cae sobre Israel!',
    'De esto se entera todo el pueblo, Efraín y los habitantes de Samaria, todos los que dicen con orgullo y con altivez de corazón:',
    '«Si se caen los ladrillos, reconstruiremos con piedra tallada; si se caen las vigas de higuera, las repondremos con vigas de cedro.»',
    'Pero el Señor ha fortalecido a los adversarios de Rezín; ha incitado a sus enemigos.',
    'Los sirios en el este y los filisteos en el oeste se comieron a Israel de un solo bocado. A pesar de todo esto, la ira de Dios no se ha aplacado; ¡su mano aún sigue extendida!',
    'Pero el pueblo no ha querido reconocer al que lo ha castigado; no ha buscado al Señor Todopoderoso.',
    'Por eso en un mismo día el Señor le cortará a Israel la cabeza y la cola, la palmera y el junco.',
    'La cabeza son los ancianos y la gente de alto rango; la cola son los profetas, maestros de mentiras.',
    'Los guías de este pueblo lo han extraviado; los que se dejan guiar son confundidos.',
    'Por eso no se complacerá el Señor en los jóvenes, ni se apiadará de huérfanos y viudas, porque todos ellos son impíos y malvados; sus labios profieren necedades. A pesar de todo esto, la ira de Dios no se ha aplacado; ¡su mano aún sigue extendida!',
    'La maldad arde como un fuego que consume zarzas y espinos, que incendia la espesura del bosque y sube luego, como torbellino, en una columna de humo.',
    'Por la ira del Señor Todopoderoso arderá en fuego la tierra. Y el pueblo será el combustible: ¡Nadie se compadecerá de su hermano!',
    'Unos comerán lo que esté a su mano derecha, pero se quedarán con hambre; otros comerán lo que esté a su izquierda, pero no quedarán satisfechos. ¡Se comerán a sus propios hijos!',
    'Manasés se comerá a Efraín, y Efraín a Manasés, y los dos juntos atacarán a Judá. A pesar de todo esto, la ira de Dios no se ha aplacado; ¡su mano aún sigue extendida!'
  ],

  // Isaías 10
  [
    '¡Ay de los que emiten decretos inicuos y publican edictos opresivos!',
    'Privan de sus derechos a los pobres, y no les hacen justicia a los oprimidos de mi pueblo; hacen de las viudas su presa y saquean a los huérfanos.',
    '¿Qué van a hacer cuando deban rendir cuentas, cuando llegue desde lejos la tormenta? ¿A quién acudirán en busca de ayuda? ¿En dónde dejarán sus riquezas?',
    'No les quedará más remedio que humillarse entre los cautivos o morir entre los masacrados. A pesar de todo esto, la ira de Dios no se ha aplacado; ¡su mano aún sigue extendida!',
    '«¡Ay de Asiria, vara de mi ira! ¡El garrote de mi enojo está en su mano!»',
    '«Lo envío contra una nación impía, lo mando contra un pueblo que me enfurece, para saquearlo y despojarlo, para pisotearlo como al barro de las calles.»',
    '«Pero esto Asiria no se lo propuso; ¡ni siquiera lo pensó! Sólo busca destruir y aniquilar a muchas naciones.»',
    '«Pues dice: ¿Acaso no son reyes todos mis jefes?»',
    '«¿No es Calnó como Carquemis? ¿No es Jamat como Arfad, y Samaria como Damasco?»',
    '«Así como alcanzó mi mano a los reinos de los ídolos, reinos cuyas imágenes superaban a las de Jerusalén y de Samaria,',
    'y así como hice con Samaria y sus dioses, también haré con Jerusalén y sus ídolos.»',
    'Cuando el Señor termine lo que va a hacer contra el monte Sión y contra Jerusalén, él dirá: «Castigaré el fruto del orgulloso corazón del rey de Asiria y la arrogancia de sus ojos.»',
    'Porque afirma: «Esto lo hizo el poder de mi mano; lo hizo mi sabiduría, porque soy inteligente. He cambiado las fronteras de los pueblos, he saqueado sus tesoros; como un guerrero poderoso he derribado a sus reyes.',
    'Como quien mete la mano en un nido, me he adueñado de la riqueza de los pueblos; como quien recoge huevos abandonados, me he apoderado de toda la tierra; y no hubo nadie que aleteara ni abriera el pico y chillara.»',
    '¿Puede acaso gloriarse el hacha más que el que la maneja, o jactarse la sierra contra quien la usa? ¡Como si pudiera el bastón manejar a quien lo tiene en la mano, o la frágil vara pudiera levantar a quien pesa más que la madera!',
    'Por eso enviará el Señor, el Señor Todopoderoso, una enfermedad devastadora sobre sus robustos guerreros. En vez de honrarlos, les prenderá fuego, un fuego como de llama ardiente.',
    'La luz de Israel se convertirá en fuego; su Santo se volverá una llama. En un solo día quemará sus espinos y consumirá sus zarzas.',
    'Destruirá de extremo a extremo el esplendor de sus bosques y de sus huertos, como enfermo carcomido por la plaga.',
    'Tan pocos árboles quedarán en su bosque que hasta un niño podrá contarlos.',
    'En aquel día ni el remanente de Israel ni los sobrevivientes del pueblo de Jacob volverán a apoyarse en quien los hirió de muerte, sino que su apoyo verdadero será el Señor, el Santo de Israel.',
    'Y un remanente volverá; un remanente de Jacob volverá al Dios Poderoso.',
    'Israel, aunque tu pueblo sea como la arena del mar, sólo un remanente volverá. Se ha decretado destrucción, abrumadora justicia.',
    'Porque el Señor, el Señor Todopoderoso, ejecutará la destrucción decretada en medio de todo el país.',
    'Por eso, así dice el Señor, el Señor Todopoderoso: «Pueblo mío, que vives en Sión, no tengas temor de Asiria. Aunque te golpee con el bastón y contra ti levante una vara, como lo hizo Egipto.',
    'Dentro de muy poco tiempo mi indignación contra ti llegará a su fin, y mi ira destruirá a tus enemigos.»',
    'Con un látigo los azotará el Señor Todopoderoso, como cuando abatió a Madián en la roca de Oreb; levantará sobre el mar su vara, como lo hizo en Egipto.',
    'En aquel día esa carga se te quitará de los hombros, y a causa de la gordura se romperá el yugo que llevas en el cuello.',
    'Llega el enemigo hasta Ayat, pasa por Migrón, y deja en Micmás su equipaje.',
    'Cruza el vado, y dice: «Acamparemos en Gueba.» Ramá se pone a temblar, y huye Guibeá, ciudad de Saúl.',
    '¡Clama a gritos, hija de Galín! ¡Escucha, Lais! ¡Pobre Anatot!',
    'Se ha puesto en fuga Madmena; los habitantes de Guebín buscan refugio.',
    'Hoy mismo se detendrá en Nob; agitará su puño contra el monte de la ciudad de Sión, el monte de Jerusalén.',
    '¡Miren! El Señor, el Señor Todopoderoso, desgaja las ramas con fuerza increíble. Los árboles más altos son talados; los más elevados son abatidos.',
    'Derriba con un hacha la espesura del bosque, y el esplendor del Líbano se viene abajo.'
  ],

  // Isaías 11
  [
    'Del tronco de Isaí brotará un retoño; un vástago nacerá de sus raíces.',
    'El Espíritu del Señor reposará sobre él: espíritu de sabiduría y de entendimiento, espíritu de consejo y de poder, espíritu de conocimiento y de temor del Señor.',
    'Él se deleitará en el temor del Señor; no juzgará según las apariencias, ni decidirá por lo que oiga decir,',
    'sino que juzgará con justicia a los desvalidos, y dará un fallo justo en favor de los pobres de la tierra. Destruirá la tierra con la vara de su boca; matará al malvado con el aliento de sus labios.',
    'La justicia será el cinto de sus lomos y la fidelidad el ceñidor de su cintura.',
    'El lobo vivirá con el cordero, el leopardo se echará con el cabrito, y juntos andarán el ternero y el cachorro de león, y un niño pequeño los guiará.',
    'La vaca pastará con la osa, sus crías se echarán juntas, y el león comerá paja como el buey.',
    'Jugará el niño de pecho junto a la cueva de la cobra, y el recién destetado meterá la mano en el nido de la víbora.',
    'No harán ningún daño ni estrago en todo mi monte santo, porque rebosará la tierra con el conocimiento del Señor como rebosa el mar con las aguas.',
    'En aquel día se alzará la raíz de Isaí como estandarte de los pueblos; hacia él correrán las naciones, y glorioso será el lugar donde repose.',
    'En aquel día el Señor volverá a extender su mano para recuperar al remanente de su pueblo, a los que hayan quedado en Asiria, en Egipto, Patros y Cus; en Elam, Sinar y Jamat, y en las regiones más remotas.',
    'Izará una bandera para las naciones, reunirá a los desterrados de Israel, y de los cuatro puntos cardinales juntará al pueblo esparcido de Judá.',
    'Desaparecerán los celos de Efraín; los opresores de Judá serán aniquilados. Efraín no tendrá más celos de Judá, ni oprimirá Judá a Efraín.',
    'Juntos se lanzarán hacia el oeste, contra las laderas de los filisteos; juntos saquearán a los pueblos del este, dejarán sentir su poder sobre Edom y Moab, y se les someterán los amonitas.',
    'Secará el Señor el golfo del mar de Egipto; pasará su mano sobre el río Éufrates y lanzará un viento ardiente; lo dividirá en siete arroyos para que lo puedan cruzar en sandalias.',
    'Para el remanente de su pueblo, para los que hayan quedado de Asiria, habrá un camino, como lo hubo para Israel cuando salió de Egipto.'
  ]
];
