export const libros = {
  "Génesis": "libros/NVI/genesis.js",
  "Éxodo": "libros/NVI/exodo.js",
  "Levítico": "libros/NVI/levitico.js",
  "Números": "libros/NVI/numeros.js",
  "Deuteronomio": "libros/NVI/deuteronomio.js",
  "Josué": "libros/NVI/josue.js",
  "Jueces": "libros/NVI/jueces.js",
  "Ruth": "libros/NVI/ruth.js",
  "1 Samuel": "libros/NVI/1_samuel.js",
  "2 Samuel": "libros/NVI/2_samuel.js",
  "1 Reyes": "libros/NVI/1_reyes.js",
  "2 Reyes": "libros/NVI/2_reyes.js",
  "1 Crónicas": "libros/NVI/1_cronicas.js",
  "2 Crónicas": "libros/NVI/2_cronicas.js",
  "Esdras": "libros/NVI/esdras.js",
  "Nehemías": "libros/NVI/nehemias.js",
  "Ester": "libros/NVI/ester.js",
  "Job": "libros/NVI/job.js",
  "Salmos": "libros/NVI/salmos.js",
  "Proverbios": "libros/NVI/proverbios.js",
  "Eclesiastés": "libros/NVI/eclesiastes.js",
  "Cantares": "libros/NVI/cantares.js",
  "Isaías": "libros/NVI/isaias.js",
};
