export const libros = {
  "Génesis": "libros/NVI/genesis.js",
  "Éxodo": "libros/NVI/exodo.js",
  "Levítico": "libros/NVI/levitico.js",
  "Números": "libros/NVI/numeros.js",
  "Deuteronomio": "libros/NVI/deuteronomio.js",
  "Josué": "libros/NVI/josue.js",
  "Jueces": "libros/NVI/jueces.js",
  "Ruth": "libros/NVI/ruth.js",
  "1 Samuel": "libros/NVI/1_samuel.js",
  "2 Samuel": "libros/NVI/2_samuel.js",
  "1 Reyes": "libros/NVI/1_reyes.js",
  "2 Reyes": "libros/NVI/2_reyes.js",
  "1 Crónicas": "libros/NVI/1_cronicas.js",
};
