// js/libros/RVC/libros.js
export const libros = {
  "Génesis": "libros/RVC/genesis.js",
  "Éxodo": "libros/RVC/exodo.js",
  "Levítico": "libros/RVC/levitico.js",
  "Números": "libros/RVC/numeros.js",
  "Deuteronomio": "libros/RVC/deuteronomio.js",
  "Josué": "libros/RVC/josue.js",
  "Jueces": "libros/RVC/jueces.js",
  "Rut": "libros/RVC/ruth.js",
  "1 Samuel": "libros/RVC/1_samuel.js",
  "2 Samuel": "libros/RVC/2_samuel.js",
  "1 Reyes": "libros/RVC/1_reyes.js",
  "2 Reyes": "libros/RVC/2_reyes.js",
  "1 Crónicas": "libros/RVC/1_cronicas.js",
  "2 Crónicas": "libros/RVC/2_cronicas.js",
  "Esdras": "libros/RVC/esdras.js",
  "Nehemías": "libros/RVC/nehemias.js",
  "Ester": "libros/RVC/ester.js",
  "Job": "libros/RVC/job.js",
  "Salmos": "libros/RVC/salmos.js",
  "Proverbios": "libros/RVC/proverbios.js",
  "Eclesiastés": "libros/RVC/eclesiastes.js",
  "Cantares": "libros/RVC/cantares.js",
  "Isaías": "libros/RVC/isaias.js",
  "Jeremías": "libros/RVC/jeremias.js",
  "Lamentaciones": "libros/RVC/lamentaciones.js",
  "Ezequiel": "libros/RVC/ezequiel.js",
  "Daniel": "libros/RVC/daniel.js",
  "Oseas": "libros/RVC/oseas.js",
  "Joel": "libros/RVC/joel.js",
  "Amós": "libros/RVC/amos.js",
  "Abdías": "libros/RVC/abdias.js",
  "Jonás": "libros/RVC/jonas.js",
  "Miqueas": "libros/RVC/miqueas.js",
  "Nahúm": "libros/RVC/nahum.js",
  "Habacuc": "libros/RVC/habacuc.js",
  "Sofonías": "libros/RVC/sofonias.js",
  "Hageo": "libros/RVC/hageo.js",
  "Zacarías": "libros/RVC/zacarias.js",
  "Malaquías": "libros/RVC/malaquias.js",
  "S.Mateo": "libros/RVC/mateo.js",
  "S.Marcos": "libros/RVC/marcos.js",
  "S.Lucas": "libros/RVC/lucas.js",
  "S.Juan": "libros/RVC/juan.js",
  "Hechos": "libros/RVC/hechos.js",
  "Romanos": "libros/RVC/romanos.js",
  "1 Corintios": "libros/RVC/1_corintios.js",
  "2 Corintios": "libros/RVC/2_corintios.js",
  "Gálatas": "libros/RVC/galatas.js",
  "Efesios": "libros/RVC/efesios.js",
  "Filipenses": "libros/RVC/filipenses.js",
  "Colosenses": "libros/RVC/colosenses.js",
  "1 Tesalonicenses": "libros/RVC/1_tesalonicenses.js",
  "2 Tesalonicenses": "libros/RVC/2_tesalonicenses.js",
  "1 Timoteo": "libros/RVC/1_timoteo.js",
  "2 Timoteo": "libros/RVC/2_timoteo.js",
  "Tito": "libros/RVC/tito.js",
  "Filemón": "libros/RVC/filemon.js",
  "Hebreos": "libros/RVC/hebreos.js",
  "Santiago": "libros/RVC/santiago.js",
  "1 Pedro": "libros/RVC/1_pedro.js",
  "2 Pedro": "libros/RVC/2_pedro.js",
  "1 Juan": "libros/RVC/1_juan.js",
  "2 Juan": "libros/RVC/2_juan.js",
  "3 Juan": "libros/RVC/3_juan.js",
  "Judas": "libros/RVC/judas.js",
  "Apocalipsis": "libros/RVC/apocalipsis.js",
};
